### PR TITLE
search support

### PR DESCRIPTION
**Pull request by typemytype**
add support for searching the big list of extensions

### CODE REVIEW

**Comment by typemytype** [comment]
this PR just got a lot bigger, with support for py3, this works now on RF1 RF2 py2 and py3...

**Comment by typemytype** [comment]
dont merge it yet, there seems to be a problem with the search list: 

vanilla seems not to be able to find the correct selection indexes

**Comment by typemytype** [comment]
this should do it :)

**Comment by typemytype** [comment]
What should be done to make this PR happen?

Thanks

**Comment by LettError** [comment]
Can we has a Mechanic for RoBoPy3 Plz?

**Comment by jackjennings** [comment]
I made a few changes locally, just trying to figure out how to reconcile them and merge…

**Pull request merged**
